import {
  REQUEST_RESEND_EMAIL,
  REQUEST_RESEND_EMAIL_SUCCESS,
  REQUEST_RESEND_EMAIL_FAILURE,
  REQUEST_SIGN_UP,
  REQUEST_SIGN_UP_SUCCESS,
  REQUEST_SIGN_UP_FAILURE,
  REQUEST_RESET_PASSWORD,
  REQUEST_RESET_PASSWORD_SUCCESS,
  REQUEST_RESET_PASSWORD_FAILURE,
  REQUEST_ADD_CURRENT_PRODUCT,
  REQUEST_ADD_CURRENT_PRODUCT_SUCCESS,
  REQUEST_ADD_CURRENT_PRODUCT_FAILURE,
  DELETE_CURRENT_PRODUCT,
  REQUEST_ADD_CURRENT_KITCHEN,
  REQUEST_ADD_CURRENT_KITCHEN_VISIBLE_SUCCESS,
  REQUEST_ADD_CURRENT_KITCHEN_INVISIBLE_SUCCESS,
  REQUEST_ADD_CURRENT_KITCHEN_FAILURE,
  DELETE_CURRENT_KITCHEN,
  REQUEST_LOGIN,
  REQUEST_LOGIN_SUCCESS,
  REQUEST_LOGIN_FAILURE,
  REQUEST_ADD_CREDIT_CARD,
  REQUEST_GET_CREDIT_CARD,
  REQUEST_UPDATE_CREDIT_CARD,
  REQUEST_DELETE_CREDIT_CARD,
  REQUEST_KIOSK_PURCHASE,
  REQUEST_ADD_CREDIT_CARD_SUCCESS,
  REQUEST_ADD_CREDIT_CARD_FAILURE,
  REQUEST_GET_CREDIT_CARD_SUCCESS,
  REQUEST_GET_CREDIT_CARD_FAILURE,
  REQUEST_UPDATE_CREDIT_CARD_SUCCESS,
  REQUEST_UPDATE_CREDIT_CARD_FAILURE,
  REQUEST_DELETE_CREDIT_CARD_SUCCESS,
  REQUEST_DELETE_CREDIT_CARD_FAILURE,
  REQUEST_KIOSK_PURCHASE_SUCCESS,
  REQUEST_KIOSK_PURCHASE_FAILURE,
} from 'nintendoapp/js/actions/actionTypes';

const loading = (state = false, action) => {
  switch (action.type) {
    case REQUEST_RESEND_EMAIL:
    case REQUEST_SIGN_UP:
    case REQUEST_RESET_PASSWORD:
    case REQUEST_ADD_CURRENT_PRODUCT:
    case REQUEST_ADD_CURRENT_KITCHEN:
    case REQUEST_LOGIN:
    case REQUEST_ADD_CREDIT_CARD:
    case REQUEST_GET_CREDIT_CARD:
    case REQUEST_UPDATE_CREDIT_CARD:
    case REQUEST_DELETE_CREDIT_CARD:
    case REQUEST_KIOSK_PURCHASE:
      return true;
    case REQUEST_RESEND_EMAIL_SUCCESS:
    case REQUEST_RESEND_EMAIL_FAILURE:
    case REQUEST_SIGN_UP_SUCCESS:
    case REQUEST_SIGN_UP_FAILURE:
    case REQUEST_RESET_PASSWORD_SUCCESS:
    case REQUEST_RESET_PASSWORD_FAILURE:
    case REQUEST_ADD_CURRENT_PRODUCT_SUCCESS:
    case REQUEST_ADD_CURRENT_PRODUCT_FAILURE:
    case DELETE_CURRENT_PRODUCT:
    case REQUEST_ADD_CURRENT_KITCHEN_VISIBLE_SUCCESS:
    case REQUEST_ADD_CURRENT_KITCHEN_INVISIBLE_SUCCESS:
    case REQUEST_ADD_CURRENT_KITCHEN_FAILURE:
    case DELETE_CURRENT_KITCHEN:
    case REQUEST_LOGIN_SUCCESS:
    case REQUEST_LOGIN_FAILURE:
    case REQUEST_ADD_CREDIT_CARD_SUCCESS:
    case REQUEST_ADD_CREDIT_CARD_FAILURE:
    case REQUEST_GET_CREDIT_CARD_SUCCESS:
    case REQUEST_GET_CREDIT_CARD_FAILURE:
    case REQUEST_UPDATE_CREDIT_CARD_SUCCESS:
    case REQUEST_UPDATE_CREDIT_CARD_FAILURE:
    case REQUEST_DELETE_CREDIT_CARD_SUCCESS:
    case REQUEST_DELETE_CREDIT_CARD_FAILURE:
    case REQUEST_KIOSK_PURCHASE_SUCCESS:
    case REQUEST_KIOSK_PURCHASE_FAILURE:
      return false;
    default:
      return state;
  }
};

export default loading;
