// ROUTE ACTIONS
export const GO_BACK = 'GO_BACK';
export const GO_TO_LOGIN = 'GO_TO_LOGIN';
export const GO_TO_SIGNUP = 'GO_TO_SIGNUP';
export const GO_TO_SCAN_PRODUCT = 'GO_TO_SCAN_PRODUCT';
export const GO_TO_SCAN_KITCHEN = 'GO_TO_SCAN_KITCHEN';
export const GO_TO_SHOPPING_CART = 'GO_TO_SHOPPING_CART';
export const GO_TO_FORGOT_PASSWORD = 'GO_TO_FORGOT_PASSWORD';
export const RESET_AND_GO_TO_LOGIN = 'RESET_AND_GO_TO_LOGIN';

// PAYMENT CARDS/MODALS ACTIONS
export const GO_TO_PAYMENT = 'GO_TO_PAYMENT';
export const GO_TO_PAYMENT_COMPLETE = 'GO_TO_PAYMENT_COMPLETE';
export const GO_TO_EDIT_PAYMENT = 'GO_TO_EDIT_PAYMENT';
export const GO_TO_ADD_PAYMENT = 'GO_TO_ADD_PAYMENT';

// UI ACTIONS
export const OPEN_RESET_PASSWORD_MODAL = 'OPEN_RESET_PASSWORD_MODAL';
export const CLOSE_RESET_PASSWORD_MODAL = 'CLOSE_RESET_PASSWORD_MODAL';

export const OPEN_RESEND_EMAIL_MODAL = 'OPEN_RESEND_EMAIL_MODAL';
export const CLOSE_RESEND_EMAIL_MODAL = 'CLOSE_RESEND_EMAIL_MODAL';

export const OPEN_REMOVE_CARD_MODAL = 'OPEN_REMOVE_CARD_MODAL';
export const CLOSE_REMOVE_CARD_MODAL = 'CLOSE_REMOVE_CARD_MODAL';

export const OPEN_USER_NOT_REGISTERED_MODAL = 'OPEN_USER_NOT_REGISTERED_MODAL';
export const CLOSE_USER_NOT_REGISTERED_MODAL = 'CLOSE_USER_NOT_REGISTERED_MODAL';

export const OPEN_USER_NOT_CONFIRMED_MODAL = 'OPEN_USER_NOT_CONFIRMED_MODAL';
export const CLOSE_USER_NOT_CONFIRMED_MODAL = 'CLOSE_USER_NOT_CONFIRMED_MODAL';

export const OPEN_INVALID_CREDENTIALS_MODAL = 'OPEN_INVALID_CREDENTIALS_MODAL';
export const CLOSE_INVALID_CREDENTIALS_MODAL = 'CLOSE_INVALID_CREDENTIALS_MODAL';

export const OPEN_INVALID_EMAIL_FP_MODAL = 'OPEN_INVALID_EMAIL_FP_MODAL';
export const CLOSE_INVALID_EMAIL_FP_MODAL = 'CLOSE_INVALID_EMAIL_FP_MODAL';

export const OPEN_EMAIL_TAKEN_MODAL = 'OPEN_EMAIL_TAKEN_MODAL';
export const CLOSE_EMAIL_TAKEN_MODAL = 'CLOSE_EMAIL_TAKEN_MODAL';

export const OPEN_SCAN_PRODUCT_PROBLEM_MODAL = 'OPEN_SCAN_PRODUCT_PROBLEM_MODAL';
export const CLOSE_SCAN_PRODUCT_PROBLEM_MODAL = 'CLOSE_SCAN_PRODUCT_PROBLEM_MODAL';

export const OPEN_SCAN_PRODUCT_NO_RECORD_MODAL = 'OPEN_SCAN_PRODUCT_NO_RECORD_MODAL';
export const CLOSE_SCAN_PRODUCT_NO_RECORD_MODAL = 'CLOSE_SCAN_PRODUCT_NO_RECORD_MODAL';

export const OPEN_SCAN_KITCHEN_PROBLEM_MODAL = 'OPEN_SCAN_KITCHEN_PROBLEM_MODAL';
export const CLOSE_SCAN_KITCHEN_PROBLEM_MODAL = 'CLOSE_SCAN_KITCHEN_PROBLEM_MODAL';

export const OPEN_SCAN_KITCHEN_NO_RECORD_MODAL = 'OPEN_SCAN_KITCHEN_NO_RECORD_MODAL';
export const CLOSE_SCAN_KITCHEN_NO_RECORD_MODAL = 'CLOSE_SCAN_KITCHEN_NO_RECORD_MODAL';

export const OPEN_PROCESSING_PAYMENT_PROBLEM_MODAL = 'OPEN_PROCESSING_PAYMENT_PROBLEM_MODAL';
export const CLOSE_PROCESSING_PAYMENT_PROBLEM_MODAL = 'CLOSE_PROCESSING_PAYMENT_PROBLEM_MODAL';

export const OPEN_ADD_PAYMENT_PROBLEM_MODAL = 'OPEN_ADD_PAYMENT_PROBLEM_MODAL';
export const CLOSE_ADD_PAYMENT_PROBLEM_MODAL = 'CLOSE_ADD_PAYMENT_PROBLEM_MODAL';

export const OPEN_DELETE_PAYMENT_PROBLEM_MODAL = 'OPEN_DELETE_PAYMENT_PROBLEM_MODAL';
export const CLOSE_DELETE_PAYMENT_PROBLEM_MODAL = 'CLOSE_DELETE_PAYMENT_PROBLEM_MODAL';

export const OPEN_UPDATE_PAYMENT_PROBLEM_MODAL = 'OPEN_UPDATE_PAYMENT_PROBLEM_MODAL';
export const CLOSE_UPDATE_PAYMENT_PROBLEM_MODAL = 'CLOSE_UPDATE_PAYMENT_PROBLEM_MODAL';

export const SHOW_THANK_YOU_SIGNUP_CONTENT = 'SHOW_THANK_YOU_SIGNUP_CONTENT';
export const HIDE_THANK_YOU_SIGNUP_CONTENT = 'HIDE_THANK_YOU_SIGNUP_CONTENT';

export const SHOW_GO_TO_ADD_PAYMENT_CONTENT = 'SHOW_GO_TO_ADD_PAYMENT_CONTENT';
export const HIDE_GO_TO_ADD_PAYMENT_CONTENT = 'HIDE_GO_TO_ADD_PAYMENT_CONTENT';

// AUTH ACTIONS
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const UPDATE_USER = 'UPDATE_USER';

// SIGN UP ACTIONS
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const REQUEST_SIGN_UP_SUCCESS = 'REQUEST_SIGN_UP_SUCCESS';
export const REQUEST_SIGN_UP_FAILURE = 'REQUEST_SIGN_UP_FAILURE';

// RESET PASSWORD ACTIONS
export const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD';
export const REQUEST_RESET_PASSWORD_SUCCESS = 'REQUEST_RESET_PASSWORD_SUCCESS';
export const REQUEST_RESET_PASSWORD_FAILURE = 'REQUEST_RESET_PASSWORD_FAILURE';

// RESEND EMAIL ACTIONS
export const REQUEST_RESEND_EMAIL = 'REQUEST_RESEND_EMAIL';
export const REQUEST_RESEND_EMAIL_SUCCESS = 'REQUEST_RESEND_EMAIL_SUCCESS';
export const REQUEST_RESEND_EMAIL_FAILURE = 'REQUEST_RESEND_EMAIL_FAILURE';

// ADD PRODUCT TO CART ACTIONS
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const DELETE_ALL_PRODUCTS_FROM_CART = 'DELETE_ALL_PRODUCTS_FROM_CART';

// GET PRODUCT ACTIONS
export const REQUEST_ADD_CURRENT_PRODUCT = 'REQUEST_ADD_CURRENT_PRODUCT';
export const REQUEST_ADD_CURRENT_PRODUCT_SUCCESS = 'REQUEST_ADD_CURRENT_PRODUCT_SUCCESS';
export const REQUEST_ADD_CURRENT_PRODUCT_FAILURE = 'REQUEST_ADD_CURRENT_PRODUCT_FAILURE';

// GET KITCHEN ACTIONS
export const REQUEST_ADD_CURRENT_KITCHEN = 'REQUEST_ADD_CURRENT_KITCHEN';
export const REQUEST_ADD_CURRENT_KITCHEN_VISIBLE_SUCCESS = 'REQUEST_ADD_CURRENT_KITCHEN_VISIBLE_SUCCESS';
export const REQUEST_ADD_CURRENT_KITCHEN_INVISIBLE_SUCCESS = 'REQUEST_ADD_CURRENT_KITCHEN_INVISIBLE_SUCCESS';
export const REQUEST_ADD_CURRENT_KITCHEN_FAILURE = 'REQUEST_ADD_CURRENT_KITCHEN_FAILURE';
export const DELETE_CURRENT_KITCHEN = 'DELETE_CURRENT_KITCHEN';

// DELETE CURRENT PRODUCT ACTION
export const DELETE_CURRENT_PRODUCT = 'DELETE_CURRENT_PRODUCT';

// CREDIT CARD ACTIONS
export const REQUEST_ADD_CREDIT_CARD = 'REQUEST_ADD_CREDIT_CARD';
export const REQUEST_ADD_CREDIT_CARD_SUCCESS = 'REQUEST_ADD_CREDIT_CARD_SUCCESS';
export const REQUEST_ADD_CREDIT_CARD_FAILURE = 'REQUEST_ADD_CREDIT_CARD_FAILURE';

export const REQUEST_GET_CREDIT_CARD = 'REQUEST_GET_CREDIT_CARD';
export const REQUEST_GET_CREDIT_CARD_SUCCESS = 'REQUEST_GET_CREDIT_CARD_SUCCESS';
export const REQUEST_GET_CREDIT_CARD_FAILURE = 'REQUEST_GET_CREDIT_CARD_FAILURE';

export const REQUEST_UPDATE_CREDIT_CARD = 'REQUEST_UPDATE_CREDIT_CARD';
export const REQUEST_UPDATE_CREDIT_CARD_SUCCESS = 'REQUEST_UPDATE_CREDIT_CARD_SUCCESS';
export const REQUEST_UPDATE_CREDIT_CARD_FAILURE = 'REQUEST_UPDATE_CREDIT_CARD_FAILURE';

export const REQUEST_DELETE_CREDIT_CARD = 'REQUEST_DELETE_CREDIT_CARD';
export const REQUEST_DELETE_CREDIT_CARD_SUCCESS = 'REQUEST_DELETE_CREDIT_CARD_SUCCESS';
export const REQUEST_DELETE_CREDIT_CARD_FAILURE = 'REQUEST_DELETE_CREDIT_CARD_FAILURE';

// KIOSK PURCHASE ACTIONS
export const REQUEST_KIOSK_PURCHASE = 'REQUEST_KIOSK_PURCHASE';
export const REQUEST_KIOSK_PURCHASE_SUCCESS = 'REQUEST_KIOSK_PURCHASE_SUCCESS';
export const REQUEST_KIOSK_PURCHASE_FAILURE = 'REQUEST_KIOSK_PURCHASE_FAILURE';

// PRODUCT VARINTS ACTIONS
export const ADD_VARIANT_TO_CART = 'ADD_VARIANT_TO_CART';
export const DELETE_VARIANT_FROM_CART = 'DELETE_VARIANT_FROM_CART';
export const DELETE_ALL_VARIANTS_FROM_CART = 'DELETE_ALL_VARIANTS_FROM_CART';

// PRODUCT QUANTITIES ACTIONS
export const ADD_QUANTITY_TO_CART = 'ADD_QUANTITY_TO_CART';
export const INCREASE_QUANTITY_IN_CART = 'INCREASE_QUANTITY_IN_CART';
export const DECREASE_QUANTITY_IN_CART = 'DECREASE_QUANTITY_IN_CART';
export const DELETE_QUANTITY_FROM_CART = 'DELETE_QUANTITY_FROM_CART';
export const DELETE_ALL_QUANTITIES_FROM_CART = 'DELETE_ALL_QUANTITIES_FROM_CART';

// PRODUCT UPC CODES
export const ADD_UPC_TO_CART = 'ADD_UPC_TO_CART';
export const DELETE_UPC_FROM_CART = 'DELETE_UPC_FROM_CART';
export const DELETE_ALL_UPCS_FROM_CART = 'DELETE_ALL_UPCS_FROM_CART';
